import type { Metadata } from "next";
import { Header } from '@/components/layout/header/header';
import { Footer } from '@/components/layout/footer';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* PAC Widget CSS */}
        <link rel="stylesheet" href="https://widget.gocruise.ru/css/app.css" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header теперь на уровне страниц, не глобально */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
